---
  title: "Coming Clean"
  description: "A description of the Coming Clean class"
  slug: "coming-clean"
  course: "addiction"
  content: 
    - 
      title: "Introduction"
      description: "Photographer Graham Macindoe and journalist Susan Stellin provide a case-study for us to consider how images are interpreted and to reflect on their enduring and potentially evolving impact. @[bio](Graham Macindoe|https://d3duklpulopo9e.cloudfront.net/fit-in/200x200/media/uploads/Graham_cropped.jpg|Graham Macindoe is a New York based photographer and an adjunct professor at Parsons The New School. His work has been widely published in the UK and the US.|https://twitter.com/grahammacindoe)"
      slug: "intro"
      type: "content"
      rich: true
    - 
      title: "Live Class"
      description: "Join the live discussion and share your thoughts via Twitter. All images are copyright Graham Macindoe."
      slug: "liveclass"
      type: "liveclass"
      duration: 1663.1
      intros: 
        - 
          title: "Jonathan Worth's Introduction"
          audio: "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-coming-clean-1530824783745-intro-64.mp3"
        - 
          audio: "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-coming-clean-1533153671915-intro-64.mp3"
          title: "Peter Anderson's Introduction"
      audio: 
        - "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-coming-clean-main-64.mp3"
        - "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-coming-clean-main-64.webm"
      classes:
        -
          location: "Newcastle University"
          date: 10-02-2018 19:00
    - 
      title: "Further Reading"
      description: "Here you’ll find links to articles relating to the work discussed and some of the themes discussed. Please tweet any of your suggestions for links to twitter.com/jonathan_worth\n #DoA1Links"
      slug: "reading"
      type: "content"
      rich: true
      carousel: 
        2: 
          image: "media/rocket-coming-clean-1531315741527-media.jpg"
          link: null
          caption: null
        3: 
          image: "media/rocket-coming-clean-1531315748339-media.jpg"
          link: null
          caption: null
        4: 
          image: "media/rocket-coming-clean-1531315772399-media.jpg"
          link: null
          caption: null
        5: 
          image: "media/rocket-coming-clean-1531315778969-media.jpg"
          link: null
          caption: null
        6: 
          image: "media/rocket-coming-clean-1531315785494-media.jpg"
          link: null
          caption: null
        7: 
          image: "media/rocket-coming-clean-1531315787838-media.jpg"
          link: null
          caption: null
        8: 
          image: "media/rocket-coming-clean-1531315790039-media.jpg"
          link: null
          caption: null
    - 
      title: "Extended Content"
      description: "Access Graham and Susan’s original full-length interviews and extra related content."
      video: "Renqf1Ltg04"
      slug: "extended"
      type: "content"
      rich: true
    - 
      title: "Homework"
      description: "Create an image or series of images that are in some way autobiographical. It doesn’t necessarily have to be a picture of your face, the contents of you pocket could say more about you than what you look like. Add a title and or caption to the image that adds another layer of meaning beyond the purely visual."
      slug: "homework"
      type: "homework"
