---
  title: "Kensington Blues"
  slug: "kensington-blues"
  course: "rocket"
  description: "A description of the Kensington Blues class"
  content: 
    - 
      title: "Introduction"
      description: "In this, the second of three episodes, new participants revisit some of the themes of episode one and their alternate perspectives enable us to build on those discussions. We move from the self-portraiture of Graham Macindoe, to the participatory practices of Jeffrey Stockbridge and his Kensington Blues project. @[bio](Jeffrey Stockbridge|https://d3duklpulopo9e.cloudfront.net/fit-in/200x200/media/uploads/jeffrey_cropped.jpg|Graduated from Drexel University with a BS in Photography in 2005. His photographs have been included in recent exhibitions at The National Portrait Gallery London, The Philadelphia Museum of Art, The Delaware Art Museum, The Delaware Center for Contemporary Arts, The Houston Center for Photography, The Wapping Project Bankside and The Print Center. Stockbridge lives and works in Philadelphia, Pennsylvania.|http://www.jeffreystockbridge.com/)"
      slug: "intro"
      type: "content"
      rich: true
    - 
      title: "Live Class"
      description: "Join the live discussion. All images displayed are Copyrighted Jeffrey Stockbridge - All Rights Reserved."
      slug: "liveclass"
      type: "liveclass"
      duration: 1554
      intros: 
        - 
          audio: "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/addiction-kensington-blues-1539097872782-intro-64.mp3"
          title: "Jonathan Worth's 1 Minute Introduction"
        - 
          audio: "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/addiction-kensington-blues-1540209274133-intro-64.mp3"
          title: "Dr Peter Anderson's 1 min intro"
      audio: 
        - "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-kensington-blues-main-64.mp3"
        - "https://s3-us-west-2.amazonaws.com/ca-us-west-2/encoded/rocket-kensington-blues-main-64.webm"
      classes: 
        - 
          location: "Newcastle University"
          date: "10-09-2018 19:00"
    - 
      title: "Further Reading"
      description: "We have curated articles around the topic of Kensington Blues and encourage you to explore the conversations happening across the web. If you find something you think should be on there, please let us know."
      slug: "reading"
      type: "content"
      rich: true
    - 
      title: "Surviving Kensington // behind the photos of 'Kensington Blues'"
      description: "What used to be a proud blue-collar neighborhood in Philadelphia is now a deteriorating haven for drugs, crime, and prostitution. Kensington is famous for the place to get your fix; and for the place you end up stuck when you’ve let your vices get the best of you."
      video: "xq2SwiBylow"
      slug: "extended"
      type: "content"
      rich: true
    - 
      title: "Homework"
      description: "Working with a subject create a collaborative image whereby the subject has a meaningful voice in how it is constructed. Ask them to contribute a caption or record a short interview which you bundle into the final piece."
      slug: "homework"
      type: "homework"
